# ══════════════════════════════════════════════════════════════════════════════
# Apply the Mean Test for a sample generated by the Linear Congruential Generator
# ══════════════════════════════════════════════════════════════════════════════
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import lineStyles

from prng.generators import linear_congruential_generator

# ── Generate Pseudorandom Numbers ──────────────────────────────────────────────
r = linear_congruential_generator(seed=83, a=141, c=53, m=1024, N=100)
r_avg = round(np.average(r), 4)
LL = round(0.5 - 1.96 / (np.sqrt(12 * 100)), 4)
UL = round(0.5 + 1.96 / (np.sqrt(12 * 100)), 4)


# ── Plot data ──────────────────────────────────────────────────────────────────
COLORS = {
    "m1": "#e06c75",  # red
    "m2": "#61afef",  # blue
    "m3": "#98c379",  # green
    "m4": "#e5c07b",  # yellow
    "m5": "#c678dd",  # purple
    "avg": "#abb2bf",
    "panel": "#282c34",
}

fig, ax = plt.subplots(figsize=(12, 6))
fig.patch.set_facecolor("#1e2127")

ax.plot(r, color=COLORS["m2"], lw=1.5, label="Numbers")
ax.axhline(LL, color=COLORS["m1"], lw=1.5, linestyle="--", label="Lower Limit")
ax.axhline(UL, color=COLORS["m1"], lw=1.5, linestyle="--", label="Upper Limit")

ax.set_facecolor(COLORS["panel"])
ax.tick_params(colors="#abb2bf", labelsize=10)
for spine in ax.spines.values():
    spine.set_edgecolor("#3e4451")
ax.grid(True, alpha=0.15, color="#abb2bf")
ax.set_xlabel("Observation", color="#abb2bf", fontsize=10, fontweight="bold")
ax.set_ylabel("Running average", color="#abb2bf", fontsize=10, fontweight="bold")
ax.legend(
    loc="upper right",
    fontsize=10,
    facecolor=COLORS["panel"],
    labelcolor="#abb2bf",
    edgecolor="#3e4451",
)

ax.set_title(
    "Crusher Processing Time Stabilization Curve",
    color="#e8d5a3",
    fontsize=14,
    fontweight="bold",
    y=1.04,
)

plt.show()
