# ══════════════════════════════════════════════════════════════════════════════
# Apply the Mean Test for a sample generated by the Linear Congruential Generator
# ══════════════════════════════════════════════════════════════════════════════
import numpy as np

from prng.generators import linear_congruential_generator

# ── Generate Pseudorandom Numbers ──────────────────────────────────────────
n_samples = 100
r = linear_congruential_generator(seed=83, a=141, c=53, m=1024, N=n_samples)

# ── Calculate Mean Test Statistics ─────────────────────────────────────────
z_score = 1.96
standard_error = 1 / np.sqrt(12 * n_samples)
r_avg = np.average(r)
lower_limit = 0.5 - (z_score * standard_error)
upper_limit = 0.5 + (z_score * standard_error)

print("=" * 34)
print(f"  {'Statistic':<20} {'Value':>8}")
print("=" * 34)
print(f"  {'Count':<20} {n:>8}")
print(f"  {'Mean':<20} {results.mean():>8.4f}")
print(f"  {'Minimum':<20} {results.min():>8.4f}")
print(f"  {'Maximum':<20} {results.max():>8.4f}")
print(f"  {'Std Deviation':<20} {results.std():>8.4f}")
print("=" * 34)

print(results)
