# ════════════════════════════════════════════════════════════════════
# Mean Test applied to a sequence of pseudorandom numbers
# generated by the Linear Congruential Generator (LCG)
# ════════════════════════════════════════════════════════════════════
import time

import numpy as np
from scipy.stats import norm

from prng.generators import linear_congruential_generator

start = time.time()

# ── Generate Pseudorandom Numbers ───────────────────────────────────
sample = linear_congruential_generator(seed=83, a=141, c=53, m=1024, N=100)
n = len(sample)

# ── Calculate Mean Test Statistics ──────────────────────────────────
alpha = 0.05
z_score = norm.ppf(1 - alpha / 2)
standard_error = 1 / np.sqrt(12 * n)
sample_mean = np.average(sample)
lower_limit = 0.5 - (z_score * standard_error)
upper_limit = 0.5 + (z_score * standard_error)
passed = lower_limit <= sample_mean <= upper_limit

end = time.time()

# ── Sample ──────────────────────────────────────────────────────────
# print(sample)
# print()

# ── Print Hypotheses ────────────────────────────────────────────────
print("Hypotheses:")
print("H0: The expected value of the sequence is 0.5 (μ = 0.5)")
print("H1: The expected value of the sequence is not 0.5 (μ ≠ 0.5)")
print()

# ── Test Results ────────────────────────────────────────────────────
print("=" * 34)
print(f"  {'Statistic':<20} {'Value':>8}")
print("=" * 34)
print(f"  {'Sample Size':<20} {n:>8}")
print(f"  {'Sample Mean':<20} {sample_mean:>8.4f}")
print(f"  {'Lower Limit':<20} {lower_limit:>8.4f}")
print(f"  {'Upper Limit':<20} {upper_limit:>8.4f}")
print(f"  {'Test Result':<20} {'Accept' if passed else 'Reject':>8}")
print("=" * 34)
print()

# ── Conclusion ─────────────────────────────────────────────────────
print("Conclusion: ", end="")
print(f"{'Do not reject H0 (μ = 0.5)' if passed else 'Reject H0 (μ = 0.5)'}")
print()

# ── Elapsed Time ───────────────────────────────────────────────────
print(f"Elapsed Time: {(end-start)*1000:.8f} ms")
