# ══════════════════════════════════════════════════════════════════════════════
# Statistical Validation: Mean Test for Pseudorandom Number Sequences
# ──────────────────────────────────────────────────────────────────────────────
# Description: Verifies the empirical mean of a sample generated by a Linear
#              Congruential Generator (LCG) against the expected uniform
#              distribution mean (μ = 0.5) using a two-tailed Z-test (α = 0.05).
# ══════════════════════════════════════════════════════════════════════════════

import matplotlib.pyplot as plt
import numpy as np

from prng.generators import linear_congruential_generator

# ── Constants & Theming ────────────────────────────────────────────────────────
COLORS = {
    "m1": "#e06c75",  # red
    "m2": "#61afef",  # blue
    "m3": "#98c379",  # green
    "m4": "#e5c07b",  # yellow
    "m5": "#c678dd",  # purple
    "avg": "#abb2bf",  # text/labels
    "panel": "#282c34",  # plot background
    "bg": "#1e2127",  # figure background
    "grid": "#abb2bf",  # grid lines
    "border": "#3e4451",  # spines
    "title": "#e8d5a3",  # title text
}


def main():
    # ── Generate Pseudorandom Numbers ──────────────────────────────────────────
    n_samples = 100
    r = linear_congruential_generator(seed=83, a=141, c=53, m=1024, N=n_samples)

    # ── Calculate Mean Test Statistics ─────────────────────────────────────────
    z_score = 1.96
    standard_error = 1 / np.sqrt(12 * n_samples)
    r_avg = np.average(r)
    lower_limit = 0.5 - (z_score * standard_error)
    upper_limit = 0.5 + (z_score * standard_error)

    # ── Plot Data ──────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor(COLORS["bg"])
    ax.set_facecolor(COLORS["panel"])

    # 1. Plot the sequence
    ax.plot(
        r,
        color=COLORS["m2"],
        lw=1.0,
        alpha=0.8,
        marker="o",
        markersize=4,
        label="Generated Sequence",
    )

    # 2. Plot the Sample Mean
    ax.axhline(
        r_avg,
        color=COLORS["m3"],
        lw=2.0,
        linestyle="-.",
        label="Sample Mean",
    )

    # 3. Plot the Confidence Limits
    ax.axhline(
        lower_limit, color=COLORS["m1"], lw=1.5, linestyle="--", label="95% Lower Limit"
    )
    ax.axhline(
        upper_limit, color=COLORS["m1"], lw=1.5, linestyle="--", label="95% Upper Limit"
    )

    # 4. Shade the acceptable region
    ax.fill_between(
        range(n_samples),
        lower_limit,
        upper_limit,
        color=COLORS["m1"],
        alpha=0.08,
        label="Acceptable Region",
    )

    # Axes styling
    ax.tick_params(colors=COLORS["avg"], labelsize=10)
    for spine in ax.spines.values():
        spine.set_edgecolor(COLORS["border"])

    # Grid and labels
    ax.grid(True, alpha=0.15, color=COLORS["grid"])
    ax.set_xlabel(
        "Observation Index", color=COLORS["avg"], fontsize=10, fontweight="bold"
    )
    ax.set_ylabel(
        "Pseudorandom Value", color=COLORS["avg"], fontsize=10, fontweight="bold"
    )

    ax.legend(
        loc="upper right",
        fontsize=10,
        facecolor=COLORS["panel"],
        labelcolor=COLORS["avg"],
        edgecolor=COLORS["border"],
    )

    ax.set_title(
        "Statistical Validation: Mean Test (95% Confidence Level)",
        color=COLORS["title"],
        fontsize=14,
        fontweight="bold",
        y=1.04,
    )

    plt.rcParams["savefig.dpi"] = 300

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
