# ══════════════════════════════════════════════════════════════════════════════
# Statistical Validation: Variance Test for Pseudorandom Number Sequences
# ──────────────────────────────────────────────────────────────────────────────
# Description: Verifies the empirical variance of a sample generated by a Linear
#              Congruential Generator (LCG) against the expected uniform
#              distribution variance (σ = 1/12) using a Chi-Square test (α = 0.05).
# ══════════════════════════════════════════════════════════════════════════════

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import chi2

from prng.generators import linear_congruential_generator

# ── Constants & Theming ────────────────────────────────────────────────────────
COLORS = {
    "m1": "#e06c75",  # red
    "m2": "#61afef",  # blue
    "m3": "#98c379",  # green
    "m4": "#e5c07b",  # yellow
    "m5": "#c678dd",  # purple
    "avg": "#abb2bf",  # text/labels
    "panel": "#282c34",  # plot background
    "bg": "#1e2127",  # figure background
    "grid": "#abb2bf",  # grid lines
    "border": "#3e4451",  # spines
    "title": "#e8d5a3",  # title text
}


def main():
    # ── Generate Pseudorandom Numbers ──────────────────────────────────────────
    n_samples = 100
    r = linear_congruential_generator(seed=83, a=141, c=53, m=1024, N=n_samples)

    # ── Calculate Variance Test Statistics ─────────────────────────────────────
    alpha = 0.05
    n = len(r)
    df = n - 1
    chi2_lower = float(chi2.ppf(alpha / 2, df))
    chi2_upper = float(chi2.ppf(1 - alpha / 2, df))
    running_var = np.array([np.var(r[:i], ddof=1) for i in range(2, n + 1)])
    r_var = float(np.var(r, ddof=1))
    lower_limit = chi2_lower / (12 * (n - 1))
    upper_limit = chi2_upper / (12 * (n - 1))

    # ── Plot Data ──────────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(12, 6))
    fig.patch.set_facecolor(COLORS["bg"])
    ax.set_facecolor(COLORS["panel"])

    # 1. Plot the running variance
    ax.plot(
        np.arange(2, n + 1),
        running_var,
        color=COLORS["m2"],
        lw=1.0,
        alpha=0.8,
        marker="o",
        markersize=4,
        label="Runnning Variance",
    )

    # 2. Plot the Sample Variance
    ax.axhline(
        r_var,
        color=COLORS["m3"],
        lw=2.0,
        linestyle="-.",
        label="Sample Variance",
    )

    # 3. Plot the Theoretical Variance
    theoretical_var = 1 / 12
    ax.axhline(
        theoretical_var,
        color=COLORS["m4"],
        lw=2.0,
        linestyle=":",
        label="Theoretical Variance",
    )

    # 4. Plot the Confidence Limits
    ax.axhline(
        lower_limit, color=COLORS["m1"], lw=1.5, linestyle="--", label="95% Lower Limit"
    )
    ax.axhline(
        upper_limit, color=COLORS["m1"], lw=1.5, linestyle="--", label="95% Upper Limit"
    )

    # 5. Shade the acceptable region
    ax.fill_between(
        range(n),
        lower_limit,
        upper_limit,
        color=COLORS["m1"],
        alpha=0.08,
        label="Acceptance Region",
    )

    # Axes styling
    ax.tick_params(colors=COLORS["avg"], labelsize=10)
    for spine in ax.spines.values():
        spine.set_edgecolor(COLORS["border"])

    # Grid and labels
    ax.grid(True, alpha=0.15, color=COLORS["grid"])
    ax.set_xlabel("Sample Size", color=COLORS["avg"], fontsize=10, fontweight="bold")
    ax.set_ylabel(
        "Sample Variance", color=COLORS["avg"], fontsize=10, fontweight="bold"
    )

    ax.legend(
        loc="lower right",
        fontsize=10,
        facecolor=COLORS["panel"],
        labelcolor=COLORS["avg"],
        edgecolor=COLORS["border"],
    )

    ax.set_title(
        "Statistical Validation: Variance Test (95% Confidence Level)",
        color=COLORS["title"],
        fontsize=14,
        fontweight="bold",
        y=1.04,
    )

    plt.rcParams["savefig.dpi"] = 300

    plt.tight_layout()
    plt.show()


if __name__ == "__main__":
    main()
